sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t anveshreddy4/docker-react -f Dockerfile.dev .

script:
 - docker run -it -e CI=true anveshreddy4/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react-version2"
  env: "DockerReactVersion2-env"
  bucket_name: "elasticbeanstalk-eu-west-2-577351765090"
  bucket_path: "docker-react-version2"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
